### ISSUE TITLE
size of tile

### ISSUE THREAD

**Issue by pimmie-ya** [Boehringer-Ingelheim/deep-learning-based-quantification-of-NAFLD-NASH#3]
Hi,

Thanks for your work for implementing and summarizing the NAFLD/NASH related methods. It is fun and helpful.

I just wondering why the size of Small tiles are 0.44 µm/px and Big tiles are 1.32 µm/px ，Is there any specific meaning like corresponding to magnification levels of 5 ×, 10×？

Thanks.

**Comment by FabianHeinemann** [comment]
Hi,

The tile dimensions are empirical with a couple of boundary conditions.

**NASH morphology:**

- **Big tiles** had to show **sufficient mesoscopic context for Fibrosis classification**1.32µm/px *299 px = 394 µm
- **Small tiles** had to show **sufficient detail for Steatosis, Inflammation, Ballooning classification** 0.44µm/px *299 px = 131 µm

**Technical conditions:**
- The **input dimension in pixels** of 299 px was given by our CNN (Inception.V3). 
- We chose to make **big tiles an integer multiple (3x) of the small tiles**, so you can create both simultaneously.
- **The Pixel Resolution of 0.44 µm/px** are 2x the pixel resolution of an AxiosScan Z1 at 20x, which we use a lot (note, other 20x systems might have different µm/px, since it depends on the whole system).

However, the dimension is not directly related to a specific magnification of a microscope.

**Comment by pimmie-ya** [comment]
> Hi,
> 
> The tile dimensions are empirical with a couple of boundary conditions.
> 
> **NASH morphology:**
> 
> * **Big tiles** had to show **sufficient mesoscopic context for Fibrosis classification**1.32µm/px *299 px = 394 µm
> * **Small tiles** had to show **sufficient detail for Steatosis, Inflammation, Ballooning classification** 0.44µm/px *299 px = 131 µm
> 
> **Technical conditions:**
> 
> * The **input dimension in pixels** of 299 px was given by our CNN (Inception.V3).
> * We chose to make **big tiles an integer multiple (3x) of the small tiles**, so you can create both simultaneously.
> * **The Pixel Resolution of 0.44 µm/px** are 2x the pixel resolution of an AxiosScan Z1 at 20x, which we use a lot (note, other 20x systems might have different µm/px, since it depends on the whole system).
> 
> However, the dimension is not directly related to a specific magnification of a microscope.

Thanks for your reply.
